### ISSUE TITLE
How to open url at new tab

### ISSUE THREAD

**Issue by zoom2009** [TrevorSundberg/puppeteer-in-electron#15]
How to open url at new tab

**Comment by GirkovArpa** [comment]
Bump!

**Comment by TrevorSundberg** [comment]
`window.loadURL` or `page.goto`. Although I'm not certain I understand the question

**Comment by TrevorSundberg** [comment]
Is this the same issue? https://github.com/TrevorSundberg/puppeteer-in-electron/issues/8

**Comment by GirkovArpa** [comment]
It looks like your linked issue is about a new window.  We need a new tab; the `pie` equivalent to:
```javascript
const newPage = await browser.newPage();
```
I was using this:
```javascript
const page =  await pie.getPage(browser, window);
const newPage = await pie.getPage(browser, window);
```
Until I realized that `page === newPage`.  My current workaround is creating a new browser and window.  But what I want is to be able to open multiple pages in 1 window, and be able to switch between them.

**Comment by TrevorSundberg** [comment]
I don't think that's a concept inside electron. I think you'll have to use another package:
