### ISSUE TITLE
Allow passing options to puppeteer.connect call

### ISSUE THREAD

**Issue by mukeshsoni** [TrevorSundberg/puppeteer-in-electron#17]
I wanted to trying pass a `slowMo` value to `puppeteer.connect` call. But it seems like `puppeteer.connect` is called with fixed values.

It would be great if the connect method took a third optional argument as extra options to be passed to `puppeteer.connect` call.

E.g.

```
  browserForPuppeteer = await pie.connect(app, puppeteer, { slowMo: 500 });
```

**Comment by TrevorSundberg** [comment]
This is a great suggestion, I'll definitely add that. Sorry for the late response!

**Comment by mukeshsoni** [comment]
Nothing to be sorry about. It's free work you are doing for others.

I am thankful for your work. Couldn't have made my application without `puppeteer-in-electron`.

**Comment by TrevorSundberg** [comment]
Sorry for taking so long. I ended up implementing this (and I still think it's a good idea to be able to pass options in that way), however the option `slowMo` actually causes some pretty bizarre behavior in electron and even breaks this project. I don't think that option was ever tested on electron.
