### ISSUE TITLE
puppeter not work after app has been built

### ISSUE THREAD

**Issue by heritechie** [TrevorSundberg/puppeteer-in-electron#2]
Hi Trevor, 
I like your library that integrating electron windows to puppetter. but I face some problem after the app has been built ,causing puppetter not work.
Is there any additional configuration for this lib to work after build?

**Comment by TrevorSundberg** [comment]
Hi Heriyanto,
I haven't tested this is a deployed electron application. I'll try this out tonight and see if I can get it working. Thanks for bringing this to my attention!

**Comment by HadrienRivere** [comment]
any update?

**Comment by zhaoyao91** [comment]
any update?

**Comment by TrevorSundberg** [comment]
Are you using `electron-builder`, `electron-forge`, or `electron-packager` or something else?

**Comment by TrevorSundberg** [comment]
Closing this issue because I tested it with `electron-packager` and it works. If anyone was using webpack, it may have been related to this PR which has now been merged:
https://github.com/TrevorSundberg/puppeteer-in-electron/pull/3
