### ISSUE TITLE
How to add puppeteer launch options?

### ISSUE THREAD

**Issue by iLoveForDi** [TrevorSundberg/puppeteer-in-electron#26]
now i want to use launch to add same options ,like 

`puppeteer.launch({
            args: [
                '--disable-web-security'
              ],
        })`

How can I do ? need help
Thanks

**Comment by TrevorSundberg** [comment]
You can do this entirely outside of the `puppeteer-in-electron` framework by doing:
```ts
const {BrowserWindow, app} = require("electron");
app.commandLine.appendArgument("disable-web-security");
```
