### ISSUE TITLE
TypeError: Cannot read property 'commandLine' of undefined

### ISSUE THREAD

**Issue by maajja** [TrevorSundberg/puppeteer-in-electron#28]
i just wannna try run puppteer inside electron,and i found in net must use puppeteer-in-electron and when i try it the ouput is 

(node:7344) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'commandLine' of undefined
    at Object.exports.connect (E:\ELECTRON 9\PUPPETEER\node_modules\puppeteer-in-electron\bin\index.js:66:22)

is that error from my code or from the module??

puppeteer v 2.0.0
node          v 14.15.4
electron     v 9.4.3

**Comment by TrevorSundberg** [comment]
Hi maajja,

That seems to indicate that the app you passed to `pie.initialize(app)` was undefined. Can you print it and see what the value is?

**Comment by maajja** [comment]
I've added `pie.initialize(app)` and the output is `UnhandledPromiseRejectionWarning: Error: The parameter 'app' was not passed in. This may indicate that you are running in node rather than electron.`

**Comment by TrevorSundberg** [comment]
Closing because it looks like the user never created `app`, and this does not repro.
