### ISSUE TITLE
The parameter 'app' was not passed in. This may indicate that you are running in node rather than electron.

### ISSUE THREAD

**Issue by fdciabdul** [TrevorSundberg/puppeteer-in-electron#38]
(node:8596) UnhandledPromiseRejectionWarning: Error: The parameter 'app' was not passed in. This may indicate that you are running in node rather than electron.

idk why , but just trying with your example code , and getting error like this 

How to fix it ?

**Comment by TrevorSundberg** [comment]
Are you running it with electron?

**Comment by fdciabdul** [comment]
> Are you running it with electron?

what do you means ?  i'm running with windows terminal

**Comment by TrevorSundberg** [comment]
You need to run electron instead of node js.
