### ISSUE TITLE
Intercept request and mock responses

### ISSUE THREAD

**Issue by blohamen** [TrevorSundberg/puppeteer-in-electron#5]
Hi. Can somebody share knowledge about intercepting requests and mocking resposes using this library?

**Comment by TrevorSundberg** [comment]
I just published version **2.0.2** that now handles this :)

At the time of writing this library electron 6 would crash if I specified `--enable-features=NetworkService`, however it looks like as of 7 this has been fixed, or at least it does not crash and seems to work correctly!

For documentation, puppeteer already has a great excemple on intercepting:
https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue

Note that if you only need read only access (not to stop or change the request) then you can list listen for `'request'` without calling `page.setRequestInterception(true)`.
