### ISSUE TITLE
error TS2345: Argument of type 'PuppeteerNode' is not assignable to parameter 

### ISSUE THREAD

**Issue by xucongyong** [TrevorSundberg/puppeteer-in-electron#59]
tsc && vite build && electron-builder --mac zip

electron/main/index.ts:10:42 - error TS2345: Argument of type 'PuppeteerNode' is not assignable to parameter of type 'typeof import("/Users/xucongyong/temp/electron-vite-project/node_modules/.store/@types+puppeteer-core@1.20.0/node_modules/@types/puppeteer-core/index")'.
  Type 'PuppeteerNode' is missing the following properties from type 'typeof import("/Users/xucongyong/temp/electron-vite-project/node_modules/.store/@types+puppeteer-core@1.20.0/node_modules/@types/puppeteer-core/index")': createBrowserFetcher, errors, devices

10   const browser = await pie.connect(app, puppeteer);
                                            ~~~~~~~~~


Found 1 error in electron/main/index.ts:10

**Comment by antoinekm** [comment]
weird workaround but will work for sure:
```
const browser = await pie.connect(app, puppeteer as any);
```
