### ISSUE TITLE
app.commandLine.getSwitchValue is not a function

### ISSUE THREAD

**Issue by designeng** [TrevorSundberg/puppeteer-in-electron#7]
devDependencies:

"electron-prebuilt-compile": "^1.8.4"

dependencies:

"puppeteer-core": "^2.1.1",
"puppeteer-in-electron": "^2.0.2",

**Comment by designeng** [comment]
Package electron-prebuilt-compile seems to be outdated.
Works perfectly with https://github.com/electron/electron-quick-start/.
Thanks!

**Comment by TrevorSundberg** [comment]
Glad you were able to find the root cause! I havent' seen `electron-prebuilt-compile` before but indeed it looks like it hasn't been updated in a while.
